name: SonarCloud
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    env:
      HEADLESS: "1"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Instalar Google Chrome
        run: |
          wget -q -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get update
          sudo apt-get install -y /tmp/chrome.deb
      - name: Verificar instalación de Chrome
        run: |
          which google-chrome || which google-chrome-stable
          google-chrome --version || google-chrome-stable --version
      - run: pip install -r requirements.txt pytest-cov
      - run: pytest --cov=pages --cov-report=xml
      - uses: SonarSource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}